<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
            [
                'name'        => 'Acessar Home',
                'route'       => 'home',
                'description' => 'Permite acessar o Dashboard',
                'created_at'  => now(),
                'updated_at'  => now()
            ],
            [
                'name'        => 'Listar Categorias',
                'route'       => 'categories.index',
                'description' => 'Permite listar categorias',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],           
            [
                'name'        => 'Criar Categoria',
                'route'       => 'categories.create',
                'description' => 'Permite criar categorias',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],          
            [
                'name'        => 'Excluir Categoria',
                'route'       => 'categories.destroy',
                'description' => 'Permite excluir categorias',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],         
            [
                'name'        => 'Alterar Categoria',
                'route'       => 'categories.edit',
                'description' => 'Permite alterar categorias',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],            
            [
                'name'        => 'Listar Empresas',
                'route'       => 'companies.index',
                'description' => 'Permite listar empresas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],            
            [
                'name'        => 'Criar Empresa',
                'route'       => 'companies.create',
                'description' => 'Permite criar empresas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],           
            [
                'name'        => 'Excluir Empresa',
                'route'       => 'companies.destroy',
                'description' => 'Permite excluir empresas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],          
            [
                'name'        => 'Alterar Empresa',
                'route'       => 'companies.edit',
                'description' => 'Permite alterar empresas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],             
            [
                'name'        => 'Excluir Documentos',
                'route'       => 'documents.destroy',
                'description' => 'Permite excluir documentos dos chamados',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],          
            [
                'name'        => 'Editar Perfil',
                'route'       => 'profile.edit',
                'description' => 'Permite alterar o perfil de acesso',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],               
            [
                'name'        => 'Listar Grupos',
                'route'       => 'groups.index',
                'description' => 'Permite listar grupos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],               
            [
                'name'        => 'Liberar Permissões',
                'route'       => 'groups.permissions.store',
                'description' => 'Permite liberar permissões de acesso',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],   
            [
                'name'        => 'Remover Permissões',
                'route'       => 'groups.permissions.destroy',
                'description' => 'Permite remover permissões de acesso',
                'created_at'  => now(),
                'updated_at'  => now(),
            ], 
            [
                'name'        => 'Criar Grupo',
                'route'       => 'groups.create',
                'description' => 'Permite criar grupos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],              
            [
                'name'        => 'Excluir Grupo',
                'route'       => 'groups.destroy',
                'description' => 'Permite excluir grupos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],             
            [
                'name'        => 'Alterar Grupo',
                'route'       => 'groups.edit',
                'description' => 'Permite alterar grupos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],                
            [
                'name'        => 'Listar Avisos',
                'route'       => 'messages.index',
                'description' => 'Permite listar avisos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],             
            [
                'name'        => 'Criar Aviso',
                'route'       => 'messages.create',
                'description' => 'Permite criar avisos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],            
            [
                'name'        => 'Excluir Aviso',
                'route'       => 'messages.destroy',
                'description' => 'Permite excluir avisos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],           
            [
                'name'        => 'Visualizar Aviso',
                'route'       => 'messages.show',
                'description' => 'Permite visualizar avisos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],              
            [
                'name'        => 'Alterar Aviso',
                'route'       => 'messages.edit',
                'description' => 'Permite alterar avisos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],              
            [
                'name'        => 'Listar Permissões',
                'route'       => 'permissions.index',
                'description' => 'Permite listar permissões',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],          
            [
                'name'        => 'Criar Permissão',
                'route'       => 'permissions.create',
                'description' => 'Permite criar permissões',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],         
            [
                'name'        => 'Excluir Permissão',
                'route'       => 'permissions.destroy',
                'description' => 'Permite excluir permissões',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],        
            [
                'name'        => 'Alterar Permissão',
                'route'       => 'permissions.edit',
                'description' => 'Permite alterar permissões',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],           
            [
                'name'        => 'Visualizar Perfil',
                'route'       => 'profile',
                'description' => 'Permite visualizar perfil de acesso',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],                   
            [
                'name'        => 'Alterar Configuração do Sistema',
                'route'       => 'settings.index',
                'description' => 'Permite alterar configuração do sistema',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],             
            [
                'name'        => 'Listar Sistemas',
                'route'       => 'systems.index',
                'description' => 'Permite listar sistemas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],              
            [
                'name'        => 'Criar Sistema',
                'route'       => 'systems.create',
                'description' => 'Permite criar sistemas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],             
            [
                'name'        => 'Excluir Sistema',
                'route'       => 'systems.destroy',
                'description' => 'Permite excluir sistemas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],            
            [
                'name'        => 'Alterar Sistema',
                'route'       => 'systems.edit',
                'description' => 'Permite alterar sistemas',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],               
            [
                'name'        => 'Listar Chamados',
                'route'       => 'tickets.index',
                'description' => 'Permite listar chamados',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],              
            [
                'name'        => 'Criar Chamado',
                'route'       => 'tickets.create',
                'description' => 'Permite criar chamados',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],             
            [
                'name'        => 'Inserir Acompanhamento',
                'route'       => 'tickets.followup',
                'description' => 'Permite inserir acompanhamentos ao chamado',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],           
            [
                'name'        => 'Responder Pesquisa de Satisfação',
                'route'       => 'tickets.feedback',
                'description' => 'Permite responder pesquisa de satisfação',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],        
            [
                'name'        => 'Visualizar Chamado',
                'route'       => 'tickets.show',
                'description' => 'Permite visualizar chamados',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],               
            [
                'name'        => 'Excluir Chamado',
                'route'       => 'tickets.destroy',
                'description' => 'Permite excluir chamados',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],            
            [
                'name'        => 'Alterar Chamado',
                'route'       => 'tickets.edit',
                'description' => 'Permite alterar chamados',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],               
            [
                'name'        => 'Listar Usuários',
                'route'       => 'users.index',
                'description' => 'Permite listar usuários',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],                
            [
                'name'        => 'Criar Usuário',
                'route'       => 'users.create',
                'description' => 'Permite criar usuários',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],               
            [
                'name'        => 'Visualizar Usuário',
                'route'       => 'users.show',
                'description' => 'Permite visualizar usuários',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],                 
            [
                'name'        => 'Excluir Usuário',
                'route'       => 'users.destroy',
                'description' => 'Permite exlcuir usuários',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],              
            [
                'name'        => 'Alterar Usuários',
                'route'       => 'users.edit',
                'description' => 'Permite alterar usuários',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],                 
        ]);
    }
}
